### ISSUE TITLE
netCDF files in the repo are not readable

### ISSUE THREAD

**Issue by jmp75** [keltonhalbert/pyvista-tornado-demo#1]
Nice work; I wanted to give it a spin and bumped into the following:
```text
OSError: [Errno -51] NetCDF: Unknown file format: b'volume_and_parcels/30m_tkeparcels_small.nc'
```
A command line `ncdump -h` also reports the issue. There may have been a file corruption when committing the binaries?

**Comment by banesullivan** [comment]
I didn't have this error... did you just do a standard clone?:
```
git clone https://github.com/keltonhalbert/pyvista-tornado-demo.git
```

**Comment by jmp75** [comment]
I downloaded a zip snapshot and unzipped with `unzip` on Linux/Debian. Never had issues like that with similar usage patterns so I did not suspect that - my bad for not double-checking with git cloning. I'll do so and close this. Thanks for the information.

**Comment by keltonhalbert** [comment]
Sorry about this - I have never used git LFS before so there's been some confusion on my end too. I've updated the README to include a link to a tarball you can download manually. Apparenly git LFS wants me to pay for bandwidth so I may remove the tracked netCDF files entirely.
